export const TAKO_FILES = [
  "albertoe.png",
  "CapSora.png",
  "cedric_alpha.png",
  "Chumbeque.png",
  "ConcussioAmi.png",
  "CyberToast.png",
  "Deceptric13.png",
  "Deracts.png",
  "DinoTakos.png",
  "Eyeye.png",
  "FlaminSarge.png",
  "Freir.png",
  "Gaah.png",
  "Gathog.png",
  "HuyK.png",
  "IcedOmachi.png",
  "InaStoleMyHARTH.png",
  "IrisPonn.png",
  "izefjc.png",
  "JustVine.png",
  "Mangu.png",
  "Pely_.png",
  "Pixaurora.png",
  "Plazma00.png",
  "Raven0815.png",
  "rid2079.png",
  "SeeyahLater.png",
  "Senki.png",
  "Squash.png",
  "subis.png",
  "third12.png",
  "Uni8.png",
  "Vaan.png",
  "Wahmaa.png",
  "wydken.png",
  "Yue.png",
  "夏雪.png",
  "11.png",
  "14.png",
  "15.png",
  "16.png",
  "17.png",
  "35.png",
  "44.png",
  "71.png",
  "A random casual.png",
  "Arthain.png",
  "Astraea.png",
  "BreadART.png",
  "Chibi RoggianX.png",
  "chuunilord.png",
  "Corp.Shephard.png",
  "Creau.png",
  "Cyber Toast.png",
  "CYtako.png",
  "DarkNess2101.png",
  "Deer Oh Dear.png",
  "DHugo.png",
  "Drebyal Draws.png",
  "eLun.png",
  "Endactam.png",
  "enicholas.png",
  "Epi.png",
  "fluffycatfish.png",
  "Fluid.png",
  "Frediloc8.png",
  "GreenFox.png",
  "Haru.png",
  "Hermit Purple.png",
  "HiloNero.png",
  "Huros.png",
  "Ironsigh.png",
  "Ithi.png",
  "Jaboll252.png",
  "Jamu(ta)ko.png",
  "Jamuko.png",
  "Jems.png",
  "Jhon. Palmer.png",
  "Joakim MF.png",
  "junblebee.png",
  "Kaede, Acolyte of Wahtcher.png",
  "keoqzzi🍜.png",
  "Kinoko.png",
  "KiwiNeko.png",
  "kshut (@shutowl).png",
  "Kurasu Kanon.png",
  "Kurosagi.png",
  "LasagnaLaffeydiction.png",
  "Lethargic.png",
  "Lienou.png",
  "LynsDoodles.png",
  "Lyudmilia.png",
  "Machi says WAH.png",
  "Mango Konata.png",
  "Mara.png",
  "McArkus.png",
  "Meap.png",
  "Melmarkt.png",
  "MiJi.png",
  "Milk.png",
  "Minja.png",
  "Neminem.png",
  "NKS5.png",
  "notaBob.png",
  "NowaruArt.png",
  "NxKarim.png",
  "Nyuusai.png",
  "OK Kei.png",
  "OutOfRice.png",
  "Overseer Olive.png",
  "popop.png",
  "ProxyZeus.png",
  "PureTako.png",
  "RCSI.png",
  "Ren.png",
  "Reyk.png",
  "Reykhebaxh.png",
  "RiDeth.png",
  "Rie Cotton Cat.png",
  "Rinh.png",
  "Scalim.png",
  "SeaRain.png",
  "SharkyDoko.png",
  "Shokuro.png",
  "SleepDeprivedFae.png",
  "SleepzyTofu.png",
  "Sock.png",
  "Spud Tako.png",
  "Squirl.png",
  "sunnyfaller.png",
  "Tahi.png",
  "Taiki Kiki.png",
  "Takedo.png",
  "Takollite.png",
  "Takomonty.png",
  "Takoster.png",
  "Teddy Bʕ´•ᴥ•`ʔ.png",
  "Teo.png",
  "The Shiv Spoon.png",
  "Thocclord.png",
  "Tornhalo.png",
  "Tung.png",
  "Valawari.png",
  "Valtaur_tw.png",
  "Vanilla Thunder.png",
  "Vantablack.png",
  "vignedev.png",
  "WindStreak.png",
  "Wydken.png",
  "Yato Tako.png",
  "Zel Maelstrom.png",
  "zeroyaka.png",
  "お兄ぎり.png",
  "イカ^10.png",
];

export const TAKO_COUNT = TAKO_FILES.length;
