import { ThemeName, Themes } from "../../types/theme";

export type { ThemeName };
export const themes: Themes = {
  Standard: {
    "--lightdark": "#F3EDFF",
    "--light-background": "#A198B3",
    "--dark-background": "#726195",
    "--light-highlight": "#ffc549",
    "--dark-highlight": "#564F68",
    "--ink-black": "#000000",
    "--background-image": "url('./Pattern.png')",
    "--text-color": "#F3EDFF",
    "--background": "#F3EDFF",
    "--shadow": "#0000001C",
    "--logo-filter": "none",
    "--title-stroke": "#ffc549",
  },
  Violet: {
    "--lightdark": "#f0eeffff",
    "--light-background": "#d1f1ff",
    "--dark-background": "#295d90",
    "--light-highlight": "#bf00ff",
    "--dark-highlight": "#86dbff",
    "--ink-black": "#2D1B3B",
    "--background-image": "url('./Pattern2.png')",
    "--text-color": "#000000",
    "--background": "#31303A",
    "--shadow": "#0000001C",
    "--logo-filter": "invert(60%) sepia(80%) saturate(400%) hue-rotate(180deg)",
    "--title-stroke": "#bf00ff",
  },
  Meconopsis: {
    "--lightdark": "#0d0d2e",
    "--light-background": "#1c205e",
    "--dark-background": "#0d0040",
    "--light-highlight": "#5db8ff",
    "--dark-highlight": "#4a7ed4",
    "--ink-black": "#b0c8ff",
    "--background-image": "none",
    "--text-color": "#ffffffff",
    "--background": "#07071e",
    "--shadow": "#0000003C",
    "--logo-filter":
      "sepia(100%) hue-rotate(190deg) brightness(0.8) contrast(1.2)",
    "--title-stroke": "#5db8ff",
  },
  Temari: {
    "--lightdark": "#181818",
    "--light-background": "#E53935",
    "--dark-background": "#656565",
    "--light-highlight": "#23242B",
    "--dark-highlight": "#ff5555ff",
    "--ink-black": "#000000",
    "--background-image": "none",
    "--text-color": "#ffffffff",
    "--background": "#5a5a5aff",
    "--shadow": "#0000001C",
    "--logo-filter":
      "invert(18%) sepia(98%) saturate(0) hue-rotate(357deg) brightness(0.9)",
    "--title-stroke": "#ff5555",
  },
  TakoTakover: {
    "--lightdark": "#1e0a3c",
    "--light-background": "#6b2fa0",
    "--dark-background": "#3d0a6e",
    "--light-highlight": "#ffc251",
    "--dark-highlight": "#ff3ab7",
    "--ink-black": "#ffc977",
    "--background-image": "none",
    "--text-color": "#f0d6ff",
    "--background": "#12003e",
    "--shadow": "#0000005C",
    "--logo-filter":
      "sepia(100%) hue-rotate(270deg) saturate(300%) brightness(0.8)",
    "--title-stroke": "#ffc251",
  },
};
