import { ThemeName, Themes } from "../../types/theme";

export type { ThemeName };
export const themes: Themes = {
  Standard: {
    "--lightdark": "#F3EDFF",
    "--light-background": "#A198B3",
    "--light-highlight": "#ffdd77",
    "--dark-highlight": "#564F68",
    "--ink-black": "#000000",
    "--background-image": "url('./Pattern.png')",
    "--text-color": "#F3EDFF",
    "--background": "#F3EDFF",
    "--shadow": "#0000001C",
    "--logo-filter": "none",
  },
  Violet: {
    "--lightdark": "#f0eeffff",
    "--light-background": "#31303A",
    "--light-highlight": "#E2B34C",
    "--dark-highlight": "#1D1B20",
    "--ink-black": "#2D1B3B",
    "--background-image": "url('./Pattern2.png')",
    "--text-color": "#ffffffff",
    "--background": "#76BAD7",
    "--shadow": "#0000001C",
    "--logo-filter": "invert(60%) sepia(80%) saturate(400%) hue-rotate(180deg)",
  },
  Meconopsis: {
    "--lightdark": "#23242B",
    "--light-background": "#23242B",
    "--light-highlight": "#0066ccff",
    "--dark-highlight": "#304759",
    "--ink-black": "#000000",
    "--background-image": "none",
    "--text-color": "#ffffffff",
    "--background": "#0100D1",
    "--shadow": "#0000001C",
    "--logo-filter": "brightness(0) invert(1) sepia(1) hue-rotate(180deg) saturate(5)",
  },
  Temari: {
    "--lightdark": "#181818",
    "--light-background": "#E53935",
    "--light-highlight": "#23242B",
    "--dark-highlight": "#ff5555ff",
    "--ink-black": "#000000",
    "--background-image": "none",
    "--text-color": "#000000ff",
    "--background": "#5a5a5aff",
    "--shadow": "#0000001C",
    "--logo-filter": "invert(18%) sepia(98%) saturate(7492%) hue-rotate(357deg) brightness(0.9)",
  },
};